pony_orm:

  provider  : mysql
  host      : localhost
  user      : root
  passwd    : root
  db        : hawrus

source:
  type: local
  path: /home/rmaia/Documentos/Projetos/infra/code/cloudflare-logshare/data/input

destination:
  type: local
  path: /home/rmaia/Documentos/Projetos/infra/code/cloudflare-logshare/data/output